baseURL = "http://elekta-foundation.org/"
languageCode = "en-us"
title = "Elekta Foundation"
theme = "hpl"
[menu]
  [[menu.mainmenu]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us/"
    weight = 1
  [[menu.mainmenu]]
    identifier = "our-team"
    name = "Our Team"
    url = "/about-us/our-team/"
    parent = "about-us"
    weight = 1
  [[menu.mainmenu]]
    identifier = "our-partners"
    name = "Our Partners"
    url = "/about-us/our-partners/"
    parent = "about-us"
    weight = 2
  [[menu.mainmenu]]
    identifier = "our-mission"
    name = "Our Mission"
    url = "/our-mission/"
    weight = 2
  [[menu.mainmenu]]
    identifier = "our-work"
    name = "Our Work"
    url = "/our-work/"
    weight = 3
  [[menu.mainmenu]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us/"
    weight = 4

# [server]
# [[server.headers]]
#   for = '/**'
#   [server.headers.values]
#     Content-Security-Policy = "default-src * unsafe-inline;connect-src *"
#     Referrer-Policy = 'strict-origin-when-cross-origin'
#     X-Content-Type-Options = 'nosniff'
#     X-Frame-Options = 'DENY'
#     X-XSS-Protection = '1; mode=report-only'